Bugfix for missing include path
D:\Build\src\Samples\HLMS\include\HLMS.h(5): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "Components/HLMS/include/OgreHlmsManager.h": No such file or directory